# Pipeline Test — Suicide Classifier

**Autores:**

| Nombre | Matrícula |
|---|---|
| Iván Alexander Ramos Ramírez | A01750817 |
| Miguel Ángel Galicia Sánchez | A01750744 |
| Aislinn Ruiz Sandoval | A01750687 |
| Víctor Alejandro Morales García | A01749831 |

In [10]:
from src.data_ingestion import ingestion
from src.preprocessing import preprocessing

In [11]:

# data ingestion

df = ingestion(
    data_url="../data/data_test_fold1.csv",
    expected_columns=[
        "user_id",
        "text_id",
        "title",
        "text",
        "is_suicide"
    ],
    text_columns=["title", "text"],
    target_column="is_suicide",
    value_true="yes",
    value_false="no" 
)
df.head(5)

Data Loaded, schema valid
Data ingestion completed.

,user_id,text_id,title,text,is_suicide,title_text
0,user1332,9a9b4a91cef5,I crave the eternal silence and slumber that c...,"Indubitably, I am not worth anything as a bein...",1,I crave the eternal silence and slumber that c...
1,user0077,d38f36ce9786,I dont know what to write here,To kill myself if I'm ugly?,1,I dont know what to write here To kill myself ...
2,user1410,6644b0f034db,Every dream I've ever had has been crushed. I'...,I had a promising academic future. I had a won...,1,Every dream I've ever had has been crushed. I'...
3,user0052,51e2fc130efa,"Nothingâ€™s changed, hope is gone, I guess I g...",,1,"Nothingâ€™s changed, hope is gone, I guess I g..."
4,user1411,adddb1851e91,Am i the only one who doesn't understand this?,One think i wont ever understand is my friends...,0,Am i the only one who doesn't understand this?...

In [12]:
# preprocessing
df = preprocessing(df, "title_text")
df.head(5)

,user_id,text_id,title,text,is_suicide,title_text,title_text_tokenized
0,user1332,9a9b4a91cef5,I crave the eternal silence and slumber that c...,"Indubitably, I am not worth anything as a bein...",1,i crave the eternal silence and slumber that c...,"[i, crave, the, eternal, silence, and, slumber..."
1,user0077,d38f36ce9786,I dont know what to write here,To kill myself if I'm ugly?,1,i dont know what to write here to kill myself ...,"[i, dont, know, what, to, write, here, to, kil..."
2,user1410,6644b0f034db,Every dream I've ever had has been crushed. I'...,I had a promising academic future. I had a won...,1,every dream i've ever had has been crushed i'v...,"[every, dream, i've, ever, had, has, been, cru..."
3,user0052,51e2fc130efa,"Nothingâ€™s changed, hope is gone, I guess I g...",,1,nothing's changed hope is gone i guess i got u...,"[nothing's, changed, hope, is, gone, i, guess,..."
4,user1411,adddb1851e91,Am i the only one who doesn't understand this?,One think i wont ever understand is my friends...,0,am i the only one who doesn't understand this ...,"[am, i, the, only, one, who, doesn't, understa..."